esphome:
  name: lh-fence-gate
  friendly_name: lh-fence-gate

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "YOUR_API_ENCRYPTION_KEY_GOES_HERE"

ota:
  password: "YOUR_OTA_PASSWORD_GOES_HERE"


switch:
  - platform: gpio
    pin:
      number: GPIO16
    id: led_red
  - platform: gpio
    pin:
      number: GPIO05
    id: led_green
  - platform: gpio
    pin:
      number: GPIO014
    id: led_blue
    
button:   
  - platform: restart
    name: "LH Fence Gate Node Restart"



binary_sensor:
  - platform: gpio
    pin:
      number: GPIO04
      mode: INPUT_PULLUP
      inverted: False
    name: "LH Fence Gate"
    device_class: door
    id: lh_fence_gate
    publish_initial_state: True
    filters:
      - delayed_on_off: 1s
    on_state:
      if:
        condition:
          binary_sensor.is_on: lh_fence_gate
        then:
          - switch.turn_on: led_red
          - switch.turn_off: led_green
        else:
          - switch.turn_on: led_green
          - switch.turn_off: led_red

interval:
  - interval: 10s
    then:
      if:
        condition:
          wifi.connected:
        then:
          - switch.turn_on: led_blue
        else:
          - switch.turn_off: led_blue


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Lh-Fence-Gate Fallback Hotspot"
    password: "YOUR_CAPTIVE_PORTAL_PASSWORD_GOES_HERE"

captive_portal:
    
